spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: discovery-server
              uri: http://discovery-server:8761
              predicates:
                - Path=/api/v1/discovery/**
              filters:
                - RewritePath=/api/v1/discovery/(?<segment>.*), /${segment}
            - id: config-server
              uri: http://config-server:9191
              predicates:
                - Path=/api/v1/config/**
              filters:
                - RewritePath=/api/v1/config/(?<segment>.*), /${segment}
            - id: identity-service
              uri: lb://identity-service
              predicates:
                - Path=/api/v1/identity/**
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/api/v1/accounts/**
            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/api/v1/transactions/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications/**
            - id: audit-service
              uri: lb://audit-service
              predicates:
                - Path=/api/v1/audit/**
  cache:
    type: simple

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
