spring:
  datasource:
    url: jdbc:postgresql://${RDS_DB_HOST}:5432/postgres
    username: pk_admin
    password: ${RDS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity-service:8081
  threads:
    virtual:
      enabled: true

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    info:
      java:
        enabled: true
      os:
        enabled: true

spring:
  cloud:
    aws:
      region:
        static: ap-south-1
      credentials:
        use-default-aws-credentials-chain: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

app:
  jwt:
    secret: "EMzbaGKrvbCeLk0Dd4abxYzVVPRADP1tJ7+vISyETcY="
    expiration-ms: 3600000
