spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/postgres
    username: postgres
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity-service:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
