spring:
  datasource:
    url: jdbc:postgresql://${RDS_DB_HOST}:5432/postgres
    username: pk_admin
    password: ${RDS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity-service:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

management.endpoints.web.exposure.include: "*"
