spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: mybank_user
    password: mybank_password

logging:
  config: classpath:logback-spring.xml
  file:
    path: /app/logs
